import { ORANGE, BLUE, WHITE } from './tokens.js';

export const LIGHT_THEME = {
  bg:       WHITE,
  page:     "#F7F7F7",
  card:     "#FAFAFA",
  cardB:    "#F0F0F0",
  border:   "#DEDEDE",
  hi:       BLUE,
  mid:      "#555555",
  low:      "#AAAAAA",
  ink:      "#F2F2F2",
  accent:   ORANGE,
  blue:     BLUE,
  trueBlue: BLUE,
  band:     BLUE,
  bandText: WHITE,
  navBg:    WHITE,
  tickerBg: "#FFF3E0",
  tickerTx: ORANGE,
  risk:     ORANGE,
  ok:       BLUE,
  warn:     "#E06000",
  grid:     "#EBEBEB",
  shadow:   "rgba(0,40,170,0.08)",
  kpiNum:   ORANGE,
  tableAlt: "#F5F5F5",
  inputBg:  "#F8F8F8",
  sigBg:    "#FFF8F0",
  findBg:   "#F8F8F8",
  redactBg: WHITE,
  redactSt: "#DDD 0,#DDD 7px,#EBEBEB 7px,#EBEBEB 9px",
  scatterOk: BLUE,
};
