export const STEPS = [
  {
    id: 'what-is-unredacted',
    targetSelector: '[data-tour="ticker"]',
    title: 'What is UN*REDACTED?',
    body: 'Unredacted tracks money relationships amongst US politics, corporations, and power. Every figure here comes from public federal disclosures.',
    placement: 'center',
    requiresTab: 'monitor',
    waitForUserAction: false,
    authGated: false,
  },
  {
    id: 'monitor-map',
    targetSelector: '[data-tour="monitor-map"]',
    title: 'The live map',
    body: 'Click any state to see its congressional delegation, live news, and active federal contracts.',
    placement: 'center',
    requiresTab: 'monitor',
    waitForUserAction: false,
    authGated: false,
  },
  {
    id: 'monitor-feeds',
    targetSelector: '[data-tour="monitor-feeds"]',
    title: 'Live news & feed',
    body: 'Stories and filings surfacing in real time. The feed updates as new FEC data and news hits.',
    placement: 'center',
    requiresTab: 'monitor',
    waitForUserAction: false,
    authGated: false,
  },
  {
    id: 'switch-to-galaxy',
    targetSelector: '[data-tour="tab-money"]',
    title: 'Explore Money Galaxy',
    body: 'Click this tab to follow the money — donations, PACs, dark money, and corporate networks.',
    placement: 'bottom',
    requiresTab: 'monitor',
    waitForUserAction: true,
    authGated: false,
  },
  {
    id: 'donor-intel',
    targetSelector: '[data-tour="subtab-intel"]',
    title: 'Donor Intelligence',
    body: 'Deep-dive profiles on individual donors: contribution history, employer, PAC affiliations, and sector breakdown.',
    placement: 'right',
    requiresTab: 'money',
    waitForUserAction: false,
    authGated: false,
  },
  {
    id: 'money-flow',
    targetSelector: '[data-tour="subtab-flow"]',
    title: 'Money Flow',
    body: 'A Sankey diagram tracing donations from employer → PAC → candidate across a full election cycle.',
    placement: 'right',
    requiresTab: 'money',
    waitForUserAction: false,
    authGated: false,
  },
  {
    id: 'dark-money',
    targetSelector: '[data-tour="subtab-darkmoney"]',
    title: 'Dark Money',
    body: '501(c)(4) organisations spend on elections without disclosing donors — the least transparent slice of campaign finance.',
    placement: 'right',
    requiresTab: 'money',
    waitForUserAction: false,
    authGated: false,
  },
  {
    id: 'corp-pacs',
    targetSelector: '[data-tour="subtab-corpacs"]',
    title: 'Corporate PACs',
    body: 'A force-directed network showing corporations, their PACs, and recipient politicians. Click any node to explore.',
    placement: 'right',
    requiresTab: 'money',
    waitForUserAction: false,
    authGated: false,
  },
  {
    id: 'ai-analyst',
    targetSelector: '[data-tour="ai-button"]',
    title: 'The AI Analyst',
    body: 'Ask any question. Four specialist agents (Policy, Spending, Donor, Corruption) route your query and synthesize findings from real federal data.',
    placement: 'left',
    requiresTab: null,
    waitForUserAction: false,
    authGated: false,
  },
];
