import { useTheme } from '../../theme/index.js'
import { FONT_MONO, ORANGE } from '../../theme/tokens.js'
import SourceFooter from '../ui/SourceFooter.jsx'

const TYPE_LABEL = {
  sector_concentration: 'SECTOR CONCENTRATION',
  dark_money_pathway:   'DARK MONEY PATHWAY',
  committee_alignment:  'COMMITTEE ALIGNMENT',
  sudden_surge:         'SUDDEN SURGE',
}

function SeverityBadge({ score }) {
  const color = score >= 8 ? '#FF4466' : score >= 5 ? '#FFB84D' : '#666'
  return (
    <span style={{
      display: 'inline-block', padding: '1px 6px', borderRadius: 2,
      fontSize: 7, fontWeight: 700, letterSpacing: 0.5,
      border: `1px solid ${color}44`, color, background: `${color}18`,
    }}>
      SEVERITY {score}/10
    </span>
  )
}

export default function PatternNarrative({ patterns = [] }) {
  const t = useTheme()
  if (!patterns.length) return null

  const primary = patterns[0]
  const others  = patterns.slice(1)

  return (
    <div style={{ padding: '10px 14px', borderBottom: `1px solid ${t.border}` }}>
      <div style={{
        background: t.cardB || t.card,
        borderLeft: `2px solid ${ORANGE}55`,
        borderRadius: '0 3px 3px 0',
        padding: '8px 10px',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 5, flexWrap: 'wrap' }}>
          <span style={{ fontSize: 7, letterSpacing: 1.5, color: ORANGE, opacity: 0.8, fontFamily: FONT_MONO }}>
            AI PATTERN ANALYSIS
          </span>
          <SeverityBadge score={primary.severity_score} />
          {primary.pattern_type && (
            <span style={{
              padding: '1px 5px', borderRadius: 2, fontSize: 7, letterSpacing: 0.5,
              border: `1px solid ${ORANGE}33`, color: ORANGE, background: `${ORANGE}12`,
              fontFamily: FONT_MONO,
            }}>
              {TYPE_LABEL[primary.pattern_type] || primary.pattern_type.toUpperCase().replace(/_/g, ' ')}
            </span>
          )}
        </div>

        <p style={{ fontSize: 11, lineHeight: 1.55, color: t.mid, margin: '0 0 4px', fontFamily: 'Roboto, sans-serif' }}>
          {primary.narrative}
        </p>

        {others.length > 0 && (
          <div style={{ marginTop: 6 }}>
            <div style={{ fontSize: 7, letterSpacing: 1, color: t.low, fontFamily: FONT_MONO, marginBottom: 3 }}>
              ALSO APPEARS IN {others.length} OTHER PATTERN{others.length > 1 ? 'S' : ''}
            </div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 3 }}>
              {others.map(p => (
                <span key={p.id} style={{
                  padding: '1px 6px', background: t.cardB || t.card,
                  border: `1px solid ${ORANGE}33`, borderRadius: 2,
                  fontSize: 7.5, color: ORANGE, fontFamily: FONT_MONO,
                  opacity: 0.8,
                }}>
                  ⚡ {p.title.slice(0, 40)}{p.title.length > 40 ? '…' : ''}
                </span>
              ))}
            </div>
          </div>
        )}
      </div>

      <SourceFooter
        s="AI analysis of FEC bulk data · generated by claude-sonnet-4-6"
        href="https://www.fec.gov/data/receipts/"
      />
    </div>
  )
}
